### ISSUE TITLE
Age method reliable?

### ISSUE THREAD

**Issue by ullenius** [personnummer/js#21]
There seems to be an issue determining the age based on the date in personal numbers:

> "The Swedish Tax Agency has been forced to create fictitious birthdays for over 2,500 individuals. The reason: Running out of available personal numbers"

https://www.dn.se/nyheter/sverige/personnumren-ar-slut-tusentals-far-fel-fodelsedag/

(translation: mine)

**Comment by frozzare** [comment]
No, we can not be sure that all birthdays are exact and if it has a fictitious birthdays it's harder to know when the real birthday is. We support personnummer and samordningsnummer right now in our packages. Fictitious birthdays will be hard since the real age exists in the public records (folkbokföringen).

If you want support for something other format, please open a issue in the meta repo.
